id: IA6B0EE5C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:46:07+00:00'
last_modified: '2022-06-08T09:12:33.520127+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27510
  title: དཔལ་གསང་བ་སྙིང་པོའི་རྒྱུད་ཀྱི་མཆན་འགྲེལ་ནོར་བུའི་སྒྲོན་མེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4333':
      image_group_id: I4477
      title: ''
      total_pages: 224
      order: 1
      base_file: 4333.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
