id: P009183
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:26:57.929765
source_metadata:
  id: bdr:W27510
  title: དཔལ་གསང་བ་སྙིང་པོའི་རྒྱུད་ཀྱི་མཆན་འགྲེལ་ནོར་བུའི་སྒྲོན་མེ
  author: ''
  volumes:
    078d6a0b24374d87974dc38db40244b6:
      image_group_id: I4477
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
